import './globals.css';
import { ReactNode } from 'react';


export const metadata = {
  title: "Next App",
  description: "Generated by next app",
};

export default function RootLayout({ children }: { children: ReactNode }) {

  return (
    <html lang="en">
      <body>{children}</body>
    </html>
  );
};
